### ISSUE TITLE
Add base constructor calls to generated dummy dlls

### ISSUE THREAD

**Issue by Panthr75** [SamboyCoding/AudicaShredder#102]
Dummy DLLs currently do not export base constructor calls, which can cause exporting issues when using [AssetRipper](https://github.com/AssetRipper/AssetRipper/issues/291). Because AssetRipper takes every type in the dummy assembly at face value, it ends up not exporting base constructors to MonoScript files, which leads to compiler errors on Scripting Level 2 (Stub methods, fields, enums, etc) in the generated Unity Project.

**Comment by ds5678** [comment]
@SamboyCoding can this be closed?
