### ISSUE TITLE
How to open IOS Unity Apps

### ISSUE THREAD

**Issue by SamueleD78** [SamboyCoding/AudicaShredder#103]
I have a decompressed IPA with a unity binary (app/Frameworks/UnitiFramework)
I tryed to open it in many ways, but it seems it's not recognized (always search for an .exe).
I tryed both from windows and linux.

How can i open it using this tool? Tyvm!

**Comment by SamboyCoding** [comment]
The `--game-path` option currently only searches for exe files and (x)apk files. If you need to specify another kind of binary (Wasm, Mach-O, NSO, etc), you need to use `--force-binary-path [path to binary]`, `--force-metadata-path [path to metadata]`, and `--force-unity-version 20XX.X.XX` - note unity version should not contain any `f1` etc on the end. Note also that in the non-pre-release builds of cpp2il, `--game-path` is marked as a required argument, so it must be present and have a value, but that value will be ignored, so you can just do something like `--game-path ignored`

**Comment by SamueleD78** [comment]
Perfect, now it loads the files! Thank you so much! I previously tried with just 1 option, but it seems all were needed.

Now he asks: `Couldn't identify a CodeRegistration address. If you know it, enter it now, otherwise enter nothing or zero to fail`

Is that the address where the global_metadata.dat file it's stored in the binary? (i got it reverse engineering it with IDA and getting it from the game memory while running, cause it was crypted)

Is it totally a different thing? ^^

**Comment by SamboyCoding** [comment]
It's a different thing, yeah. If you can join my discord server (linked in the readme) we can take a look to see what's going on
