### ISSUE TITLE
Failed to perform analysis on method (Vacation Simulator)

### ISSUE THREAD

**Issue by TrevTV** [SamboyCoding/AudicaShredder#11]
Trying to get some basic idea on how scripts in Vacation Simulator work but when trying to run the latest commit (commit_06f6ecc658c6378f90266e7e51b8672abab6c467 as of now) it is giving out many errors relating to "Failed to perform analysis on method" which causes it to not create method files for many of the scripts (including the one I needed Cpp2IL for in the first place). Vacation Simulator is currently on 2018.4.14 with IL2CPP version 24.1 in case you need to know.

[cpp2il-output.txt](https://github.com/SamboyCoding/Cpp2IL/files/6290910/cpp2il-output.txt)

**Comment by SamboyCoding** [comment]
Yes there's a number of issues, the root cause of which is generics, that I'm trying to fix, but Cecil is being difficult.

**Comment by SamboyCoding** [comment]
Try again with the latest commit - it should hopefully work a little better.

**Comment by TrevTV** [comment]
Working great now, thank you
