### ISSUE TITLE
Crash when decompiling a Unity APK

### ISSUE THREAD

**Issue by Andrew-Eathan** [SamboyCoding/AudicaShredder#112]
![image](https://user-images.githubusercontent.com/42521608/168122148-7b4180eb-7b84-49cf-8722-2e347512aa41.png)
sorry if this might not be enough info to work with, it was running for ~15 minutes, gathered about 4gb of ram before it died, the game i was decompiling is "DATA WING" and i'm on windows 7 if that helps

**Comment by SamboyCoding** [comment]
Arm64 binaries just really don't like custom attributes at the moment, use the latest nightly from the new-analysis branch, and run cpp2il with the `--simple-attribute-restoration` argument, then you should get more usable output.
