### ISSUE TITLE
Failed to process type <Module>

### ISSUE THREAD

**Issue by MikaCybertron** [SamboyCoding/AudicaShredder#118]
`Unhandled exception. System.Exception: Failed to process type <Module> (module GameDevWare.Dynamic.Expressions.dll, declaring type ) in GameDevWare.Dynamic.Expressions.dll
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Cpp2IL.Core.AssemblyPopulator.GetInjectedAttributes(TypeDefinition ilTypeDefinition)
   at Cpp2IL.Core.AssemblyPopulator.CopyIl2CppDataToManagedType(Il2CppTypeDefinition cppTypeDefinition, TypeDefinition ilTypeDefinition, Boolean suppressAttributes)
   at Cpp2IL.Core.AssemblyPopulator.PopulateStubTypesInAssembly(Il2CppImageDefinition imageDef, Boolean suppressAttributes)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.AssemblyPopulator.PopulateStubTypesInAssembly(Il2CppImageDefinition imageDef, Boolean suppressAttributes)
   at Cpp2IL.Core.Cpp2IlApi.MakeDummyDLLs(Boolean suppressAttributes)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)`

![image](https://user-images.githubusercontent.com/45533977/175748637-fd74b2b3-6c81-4d5c-91be-cefc53b81de1.png)

**Comment by SamboyCoding** [comment]
Out of curiosity, can you check to see if you can load this apk in the new pre-release I published today? Just to see if there is a bug I have already fixed.

**Comment by MikaCybertron** [comment]
> Out of curiosity, can you check to see if you can load this apk in the new pre-release I published today? Just to see if there is a bug I have already fixed.

i have test it with the new pre-release you published today and it just not work in this exe file `Cpp2IL-2022.1.0-pre-release.6-Windows.exe)`

but working fine with `Cpp2IL-2022.1.0-pre-release.6-Windows-Netframework472.zip`

**Comment by SamboyCoding** [comment]
They should behave identically, what does the one that doesn't work say?

**Comment by MikaCybertron** [comment]
> They should behave identically, what does the one that doesn't work say?

the error is in the first message

**Comment by SamboyCoding** [comment]
It's literally impossible for it to do the same thing on the pre-release build, that code doesn't exist any more.

**Comment by MikaCybertron** [comment]
> It's literally impossible for it to do the same thing on the pre-release build, that code doesn't exist any more.

nah thats the error said it self, but it just not work in this `Cpp2IL-2022.1.0-pre-release.6-Windows.exe` and working fine with  `Cpp2IL-2022.1.0-pre-release.6-Windows-Netframework472.zip`

so nothing big deals and maybe it just the code doesn't support in `Cpp2IL-2022.1.0-pre-release.6-Windows.exe`

**Comment by SamboyCoding** [comment]
That is my point, the windows exe and the netframework zip have exactly the same code, just targeting different runtimes, so there shouldn't be any issue where one works and the other doesn't. What I want to know is what error message you get with the pre-release exe file, because the original error message you posted when you opened this issue was for the normal release, not the pre-release.

**Comment by MikaCybertron** [comment]
> That is my point, the windows exe and the netframework zip have exactly the same code, just targeting different runtimes, so there shouldn't be any issue where one works and the other doesn't. What I want to know is what error message you get with the pre-release exe file, because the original error message you posted when you opened this issue was for the normal release, not the pre-release.

ahh i misunderstanding haha, i just test it again and it working fine on pre-release and just not work on normal release

**Comment by SamboyCoding** [comment]
Okay, in that case I will try and find a fix for the normal release tomorrow.
