### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by RealSmecks** [SamboyCoding/AudicaShredder#12]
Hello. I am currently trying to use Cpp2Il on a game that uses 2019.4.22. However when attempting to use the tool, it gives out an overflow exception. I am currently using "commit_d02ef41b68755d6b39807131ffe135749a3644f5"

This is the command I am using: .\Cpp2IL-Win.exe --game-path "C:\Program Files (x86)\Steam\steamapps\common\*GAME NAME*"

This is the full log:
`===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Running on Win32NT
Determined game's unity version to be 2019.4.22
Initializing Metadata...
Using IL2CPP Metadata version 24.3
        Reading image definitions...OK (6.1843 ms)
        Reading type definitions...10504 OK (255.7858 ms)
        Reading interface offsets...OK (18.076 ms)
        Reading vtable indices...OK (25.7729 ms)
        Reading method definitions...OK (588.1665 ms)
        Reading method parameter definitions...OK (185.2095 ms)
        Reading field definitions...OK (154.8536 ms)
        Reading default field values...OK (43.1683 ms)
        Reading default parameter values...OK (8.7643 ms)
        Reading property definitions...OK (80.0201 ms)
        Reading interface definitions...OK (4.0538 ms)
        Reading nested type definitions...OK (0.227 ms)
        Reading event definitions...OK (0.4746 ms)
        Reading generic container definitions...OK (2.3406 ms)
        Reading generic parameter definitions...OK (3.5391 ms)
        Reading string definitions...OK (60.9883 ms)
        Reading usage data...OK (604.3421 ms)
        Reading field references...OK (1.3127 ms)
        Reading attribute types...OK (13.3477 ms)
        Building Lookup Table for field defaults...OK (9.2839 ms)
Initialized Metadata in 2267ms
Searching Binary for Required Data...
Reading PE File Header...OK (12.1218 ms)
        Image Base at 0x180000000
        DLL is 64-bit
Attempting to locate code and metadata registration functions...
        -Searching for MetadataReg...
        -Searching for CodeReg...
                Using mscorlib full-disassembly approach to get codereg, this may take a while...
Got Binary codereg: 0x18247BFE8, metareg: 0x18247F860 in 431ms.
Initializing Binary...
        Reading generic instances...OK (40.8275 ms)
        Reading generic method pointers...

Fatal Exception initializing LibCpp2IL!
System.OverflowException: Arithmetic operation resulted in an overflow.
   at LibCpp2IL.ClassReadingBinaryReader.ReadClassArrayAtRawAddr[T](Int64 offset, Int64 count)
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Cpp2IlTasks.InitializeLibCpp2Il(Cpp2IlRuntimeArgs runtimeArgs)

Waiting for you to press enter - feel free to copy the error...`

How would I go around fixing this. Is there another argument that is needed? Also, thank you for making this tool. Sadly, I haven't been able to use it fully yet, but I appreciate your work.

**Comment by SamboyCoding** [comment]
Hi, this usage is correct - that is to say, you're doing everything right as far as I can see - but without knowing what the game is, I can't investigate myself to find out what is causing the error.  My first guess would be that this game is using some sort of protection - but it could also be that I have made a mistake.

So, if you could tell me what the game is, that would be excellent, thanks.

**Comment by RealSmecks** [comment]
> Hi, this usage is correct - that is to say, you're doing everything right as far as I can see - but without knowing what the game is, I can't investigate myself to find out what is causing the error. My first guess would be that this game is using some sort of protection - but it could also be that I have made a mistake.
> 
> So, if you could tell me what the game is, that would be excellent, thanks.

Hello. The game name is "Pixel Worlds". I don't think it has protection, just IL2CPP as far as I'm aware, but I'm not 100% sure. Thank you for your response.

**Comment by SamboyCoding** [comment]
Alright, I'll give it a test and let you know soon.

**Comment by SamboyCoding** [comment]
Ok, this issue is related to unity 2019.4.21+ (metadata v24.5), which is not yet supported. This is the first game I've observed in the wild using this version, so I'll try to get this patched for you sometime soon - but it won't be right now, I'm afraid.

**Comment by RealSmecks** [comment]
> Ok, this issue is related to unity 2019.4.21+ (metadata v24.5), which is not yet supported. This is the first game I've observed in the wild using this version, so I'll try to get this patched for you sometime soon - but it won't be right now, I'm afraid.

All good man. I appreciate you taking the time to try the game with the tool for me. The developers keep updating their Unity version for some reason.

**Comment by SamboyCoding** [comment]
Support for v24.5 is added in Milestone Release 2021.0, so I'm closing this issue now.
