### ISSUE TITLE
Strange bug

### ISSUE THREAD

**Issue by Gorge123** [SamboyCoding/AudicaShredder#129]
Hi!
Every method has such error:
Generated IL:
	Action of type Cpp2IL.Core.Analysis.Actions.ARM64.Arm64ReturnAction at (0xAC1620) is corrupt (Return value has a type of System.Int64, expecting an object of type Shared.Entities.InventoryItem) and cannot be created as IL. Aborting here.

and in generated dll only 'return null' on every method. 

https://anonfiles.com/t0b8b637y1/test_zip

**Comment by SamboyCoding** [comment]
I doubt every single method has the same issue, and regardless, Arm64 support is still very limited. The return null thing is probably down to you not enabling saving of generated IL to the DLL file as described in the readme.
