### ISSUE TITLE
support metadata v23

### ISSUE THREAD

**Issue by ghost** [SamboyCoding/AudicaShredder#13]
any plan for making it support metadata v23 ?

**Comment by SamboyCoding** [comment]
I didn't have any plans to do so. Do you have an example of something using v23?

**Comment by ghost** [comment]
Yes, but its an android game. 
The latest version is protected, 
it show error `array index out of bounds` when i try dump it with il2cppdumper
So i would recommend use the outdated version 
Link : [here](https://m.apkpure.com/id/call-of-duty-mobile/com.activision.callofduty.shooter/download/2449-APK?from=versions%2Fversion)

**Comment by RingyRing** [comment]
_Apollo Justice - Ace Attorney_ uses an even older version of Il2Cpp, v21.

**Comment by SamboyCoding** [comment]
v23 is now supported on the dev branch as of 2c7140328e00a67884a66ec2bf14b600969c8557
