### ISSUE TITLE
Exit with InvalidOperationException

### ISSUE THREAD

**Issue by ardittristan** [SamboyCoding/AudicaShredder#14]
When running the tool on Gunfire Reborn it errors on fixing overrides and then generates nothing except empty folders.

[verbose log](https://gist.github.com/ardittristan/a2ef69c84e7c9d74dcf14529094eef50)
using version [commit_bd7cfc75ef471db90e965216d4b6cc3c67cc2048](https://github.com/SamboyCoding/Cpp2IL/releases/tag/commit_bd7cfc75ef471db90e965216d4b6cc3c67cc2048)

**Comment by SamboyCoding** [comment]
Will take a look for you. Thanks for reporting! Is the game free? If not, can you upload the global_metadata.dat file and the GameAssembly.dll so I can run it myself?

**Comment by SamboyCoding** [comment]
Actually, I've just pushed a commit which should at least result in it not dying. It'll log a warning, and move on (in theory). Can you try with [this commit](https://github.com/SamboyCoding/Cpp2IL/releases/tag/commit_bf026f6e60169dccbb1750d770df0d756eca2138)

**Comment by SamboyCoding** [comment]
Also, assuming that works, can you upload the log file (no need for verbose), so I can check exactly what was dying?

**Comment by ardittristan** [comment]
[here's](https://gist.github.com/ardittristan/f89916ab3cfeda1e67cdc1ec390eb500) the new logs created with the referenced commit, it does create files now.  
Do you still need the gameassembly and metadata?

**Comment by ardittristan** [comment]
oh, and [this](https://gist.github.com/ardittristan/d0462fac2a7309fec4f872eb8adaba84) is with the [latest](https://github.com/SamboyCoding/Cpp2IL/releases/tag/commit_3e358d760490dcddaa6098d83f352beee81b1ebb) commit.

**Comment by SamboyCoding** [comment]
Okay that looks a lot more normal now - all the issues in that log are known as-yet-unsupported things in analysis. The 4 failed explicit override restores are probably down to that one specific library, and maybe at some point I'll pick up gunfire reborn and try to take a look, but they're no big deal.

Don't worry about giving me the files now, it works as well as any other game now.

**Comment by SamboyCoding** [comment]
If you're happy, then I'll close this issue (or you can)

**Comment by ardittristan** [comment]
Thanks!
