### ISSUE TITLE
Failed to process type Assembly-Csharp.dll

### ISSUE THREAD

**Issue by orcun9988** [SamboyCoding/AudicaShredder#141]
hello I got error in melonloader idk why

![unknown](https://user-images.githubusercontent.com/58307867/192525664-d86fa31b-8376-4c9d-b034-21e04cd0aa29.png)

**Comment by nitrog0d** [comment]
Phasmophobia not supported

**Comment by orcun9988** [comment]
> Phasmophobia not supported 

I already fixed thx anywayy you can close ticket
