### ISSUE TITLE
Can't dump

### ISSUE THREAD

**Issue by IroniaTheMaster** [SamboyCoding/AudicaShredder#169]
Hello.
So, I'm trying to do this with a decrypted metadata, I managed to decrypt it, however, when testing on Il2CppDumper-v6.7.25 it works, but in this program, it doesn't work. (it's from an android game). Any solution? Some tell me to put the global-metadata.dat in the visual code. but how is this possible? xD

**Comment by SamboyCoding** [comment]
Dumped ELF files require additional support which I have little interest in implementing

**Comment by IroniaTheMaster** [comment]
> 

are you talking about libil2cpp.so? or the global-metadata.dat? how do i get a solution?

**Comment by SamboyCoding** [comment]
libil2cpp.so

**Comment by IroniaTheMaster** [comment]
> libil2cpp.so

is there any way to convert this?

**Comment by IroniaTheMaster** [comment]
> libil2cpp.so

is there any way to convert this?
