### ISSUE TITLE
Error while building assemblies

### ISSUE THREAD

**Issue by bence0585** [SamboyCoding/AudicaShredder#197]
Reversing the game "Fishing Planet" on build Milestone 2022.0.7 returns with an error.
Running it with the latest preview (Milestone Preview: 2022.1.0#10), the tool finishes but I don't get a dummy-dll output.

System: Win11 x64
Game version: 2020.3.40
IL2CPP version: 27.1

Folder of game:
![explorer_FnkaWZpdKW](https://user-images.githubusercontent.com/52159134/209451448-83b04d2c-d10e-41cf-8ce7-e32f5a9733c7.png)

Output in terminal:
![WindowsTerminal_fQaLQJl9O6](https://user-images.githubusercontent.com/52159134/209451444-917cf11e-83a2-4164-9d88-d580d7062d87.png)

Output log:
https://gist.github.com/bence0585/10fac948fbb40aadab3e1edecfab9da8

**Comment by SamboyCoding** [comment]
If you just want dummy-dll output, you can run the latest preview and add `--output-as dummydll` to the command line

**Comment by bence0585** [comment]
That was exactly what I was looking for.
Thank you so much for all the work you do, and may your holidays be full of warmth and cheer!
