### ISSUE TITLE
Invalid .NET 7 build (upload) path

### ISSUE THREAD

**Issue by JohnFedorchak** [SamboyCoding/AudicaShredder#216]
No net7 win-x64 artifact is made because the following string contains `ne7.0` and not `net7.0`.

`path: ./${{ matrix.project }}/bin/Release/ne7.0/${{ matrix.runtimeIdentifier }}/publish/${{ matrix.project }}${{ steps.set-vars.outputs.extension }}
`

**Comment by SamboyCoding** [comment]
Ah, well that's embarrassing. Doesn't matter anyway, the move from net6 -> net7 broke CommandLineParser and I haven't dug into why yet.
