### ISSUE TITLE
ASM to IL process gets the parameters wrong for non instance methods in Il2Cpp versions <= 24

### ISSUE THREAD

**Issue by lilmayofuksu** [SamboyCoding/AudicaShredder#218]
In il2cpp versions <= 24, every generated method by il2cpp has a "__this" parameter. This was removed in the next versions however current version of Cpp2IL doesn't handle this scenario

So every call to static/extern function gets translated wrong. The code generated by il2cpp transpiler also comments the parameter as 
"static, unused".
![image](https://user-images.githubusercontent.com/11977128/232551520-b63cb298-8b67-43f3-89af-48a696840c82.png)
![image](https://user-images.githubusercontent.com/11977128/232551870-1de0f7ab-099d-4945-9de5-78da11c944db.png)

**Comment by nitrog0d** [comment]
ayy lamo

**Comment by lilmayofuksu** [comment]
neteor
