### ISSUE TITLE
Help About Methods

### ISSUE THREAD

**Issue by NobodyOffcal** [SamboyCoding/AudicaShredder#222]
"CPP2IL failed to recover any usable IL for this method" how i could fix that i use GameAssembly.dll and just-give-me-dlls-asap-dammit

**Comment by nitrog0d** [comment]
It means what the message says, there's no fix, maybe in the future the IL regeneration will impro

**Comment by NobodyOffcal** [comment]
is there any way to dump specific method i really need one

**Comment by nitrog0d** [comment]
I don't think you can with Cpp2IL currently if it couldn't recover, however can use reverse engineering tools like IDA/Ghidra/Binja/whatever, but I'm not guiding you through that
