### ISSUE TITLE
Could not initialize assembly manager

### ISSUE THREAD

**Issue by ProbiusPrime** [SamboyCoding/AudicaShredder#228]
![console](https://github.com/SamboyCoding/Cpp2IL/assets/89365323/5260660a-7012-4bbc-b726-ac44996fa4db)

CMD encountered this error while using another program (AssetRipper).

Is Unity 22.3.3f1 still unsupported?

**Comment by ds5678** [comment]
Reference: https://github.com/AssetRipper/AssetRipper/issues/915

**Comment by ItzFAILURE** [comment]
any updates n this problem?

**Comment by ds5678** [comment]
Development on Cpp2IL has been fairly slow with no one actively maintaining it. If my Patreon for AssetRipper does well, I'll start posting polls, so that subscribers can vote on development priorities. Diverting some attention to Cpp2IL would be one of the available options to vote on.

**Comment by ItzFAILURE** [comment]
> Development on Cpp2IL has been fairly slow with no one actively maintaining it. If my Patreon for AssetRipper does well, I'll start posting polls, so that subscribers can vote on development priorities. Diverting some attention to Cpp2IL would be one of the available options to vote on.

i see, so considering im already subbed the only thing i can do RN is ignore my current project and wait for the poll.

**Comment by ds5678** [comment]
This has been resolved.
