### ISSUE TITLE
Options to Generate Symbol Maps Only?

### ISSUE THREAD

**Issue by dlbuhtig4096** [SamboyCoding/AudicaShredder#236]
Cpp2IL works fine, but I need a feature to dump symbol map and load it to disassemblers like IDA or Ghidra for debugging, just like what IL2CppDumper does. Are there any way to do so?

I have tried [IL2CppDumper](https://github.com/Perfare/Il2CppDumper) but it failed. [Please see the issue I opened there for details](https://github.com/Perfare/Il2CppDumper/issues/747).

And, various exceptions occurs during analyzing, I don't sure if that is normal. [Here is log, just in case it helps](https://drive.google.com/file/d/1U17ai0dC0koviu_4_ao72U5P6lHZ4M9B).

Many thanks.

**Comment by nitrog0d** [comment]
Feel free to PR!
