### ISSUE TITLE
Where can I find il2cpp executable and libs to start reverse engineering it for helping this project ? 

### ISSUE THREAD

**Issue by b00tkitism** [SamboyCoding/AudicaShredder#239]

**Comment by ds5678** [comment]
For Windows games, the two IL2Cpp files are `GameAssembly.dll` and `global-metadata.dat`.

**Comment by dream811** [comment]
@ds5678 
How to reverse GameAssembly.dll?
Please share with me.

**Comment by ds5678** [comment]
It should be next to the exe.
