### ISSUE TITLE
[BUG] "Failed to perform analysis: System.OverflowException"

### ISSUE THREAD

**Issue by EliteMasterEric** [SamboyCoding/AudicaShredder#25]
I am attempting to run analysis on the IL2CPP Unity game Gems of War, and encountered the following error when running:

```
[Warn] [Analyze] Failed to perform analysis on method System.Void ArtifactDisplayData::StopRunningCoroutines()
While analysing instruction lea eax,[esi*4+10h] at 0x10470934
Got exception: System.OverflowException: Provided address, 0x10, was less than image base, 0x10000000
   at LibCpp2IL.PE.PE.MapVirtualAddressToRaw(UInt64 uiAddr)
   at Cpp2IL.Core.Analysis.AsmAnalyzer.CheckForTwoOpInstruction(Instruction instruction)
   at Cpp2IL.Core.Analysis.AsmAnalyzer.PerformInstructionChecks(Instruction instruction)
   at Cpp2IL.Core.Analysis.AsmAnalyzer.AnalyzeMethod()
```

This error occurs a couple dozen times during analysis.

I am not sure what the issue is. It's possible the issue is related to the game's executable being a 32-bit build.

If needed, I can perform additional testing, provide more logs, or test development builds.

The version used is milestone `Cpp2IL 2021.3.0.0`.

**Comment by MishaTy** [comment]
I have the same issue.

**Comment by SamboyCoding** [comment]
Sorry, I saw this the other day, and yeah it's a problem with 32-bit games. Also interesting to note that gems of war is il2cpp now - used to play that.

I'll try and take a look at what is causing the issue here.
