### ISSUE TITLE
How to get dump.cs from  GameAssembly.dll and global-metadata.dat

### ISSUE THREAD

**Issue by dream811** [SamboyCoding/AudicaShredder#272]
I tried with Il2CppInspector(https://github.com/djkaty/Il2CppInspector) andIl2CppDumper(https://github.com/Perfare/Il2CppDumper).
But I got failed.

Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor
The supplied metadata file is not of a supported version (29).
Analyze IL2CPP data: 0.50 sec

I attached my GameAssmebly.dll and global-metadata.dat
https://drive.google.com/file/d/19iDi8wukrwpQlobT88qx1gzEHPhza6cP/view?usp=sharing
https://drive.google.com/file/d/1VOSeuzfGBw22jWOgYGLENmdhcbVdJllZ/view?usp=sharing
Please give me a hint.
Thanks

**Comment by CamelCaseName** [comment]
give https://github.com/BepInEx/Il2CppInterop/releases a try

**Comment by CamelCaseName** [comment]
this has an example of the command line arguments you could use https://github.com/BepInEx/Il2CppInterop/blob/master/Documentation/Command-Line-Usage.md#basic-usage-generate-proxy-assemblies

**Comment by SamboyCoding** [comment]
Closing in favor of #303
