### ISSUE TITLE
Dump fails due invalid metadata

### ISSUE THREAD

**Issue by Umbra999** [SamboyCoding/AudicaShredder#273]
The dump fails due magic number check in the metadata. I would assume its encrypted? But no idea where to start to fix it on my own 
![Bild_2024-02-16_025910369](https://github.com/SamboyCoding/Cpp2IL/assets/69671761/190b671a-ded7-4f02-a641-d36d38b5b2f6)

**Comment by davispuh** [comment]
I'm getting same issue, header shows as `0x0059484D` version `0`

```
$  hexdump -n 48 -C global-metadata.dat
00000000  4d 48 59 00 00 00 00 00  df 4f 23 98 f4 76 1f 40  |MHY......O#..v.@|
00000010  da 33 6f 52 c5 f5 e3 44  33 db 58 27 9f 86 97 6b  |.3oR...D3.X'...k|
00000020  c9 16 25 d0 45 3d e2 15  fd 0d 66 49 20 48 7f 5a  |..%.E=....fI H.Z|
00000030
```

**Comment by SamboyCoding** [comment]
> MHY
not getting any support with that on github because I value not having my repo taken down. Anyway to answer the original question of the issue, encrypted metadata you'd eventually be able to write a plugin but I'm not going to even attempt to write support for any of this stuff into cpp2il itself.
