### ISSUE TITLE
Failed to Locate any executable

### ISSUE THREAD

**Issue by mitakabg20** [SamboyCoding/AudicaShredder#274]
I have been trying for the past few months to decompile an android game in AssetRipper, and i tried fixing the scripts, and went to Il2cpp dumper to get the DummyDLLs but it gives empty methods, so i went into Cpp2IL and i gave the directory to the APK file and i get an error here is what i typed

C:\Users\milev>cd C:\Users\milev\Downloads\Cpp2IL-2022.0.7-Windows-Netframework472

C:\Users\milev\Downloads\Cpp2IL-2022.0.7-Windows-Netframework472>Cpp2IL.exe --game-path C:\Users\milev\Downloads\IS8APK
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.

[Info] [Program] Running on Win32NT
[Fail] [Program] Execution Failed: Failed to locate any executable in the provided game directory. Make sure the path is correct, and if you *really* know what you're doing (and know it's not supported), use the force options, documented if you provide --help.

**Comment by SamboyCoding** [comment]
For apks, provide the path to the apk itself in --game-path, not the directory containing it.

**Comment by mitakabg20** [comment]
Oh, i get it, thank you!
