### ISSUE TITLE
Documentation on wasm?

### ISSUE THREAD

**Issue by JonJon565** [SamboyCoding/AudicaShredder#286]
Hi, How do you get the IL code for a *.wasm.br / *.wasm.unityweb file?
your program has all these --just-give-me-dlls-asap-dammit arguments which is really unprofessional and your documentation doesn't seem to show how to do unity web games.
If you can point me in the right direction then that would be great.

**Comment by SamboyCoding** [comment]
> really unprofessional

this is hobbyist software that I make in my free time for free. I am under no obligation to even pretend to be professional, so I do not. if you cannot handle a little whimsy, that's not my problem or fault.

> IL code for wasm

as the readme clearly indicates, no analysis support is implemented for wasm. you can do a dump, using the --force- options that are provided in the command line help from the app itself and which are intentionally absent from the readme, but that will not give you any IL.

also, for future reference, it is not considered "professional" to create a github issue to ask a question. that is what the discussions section is for.
