### ISSUE TITLE
Metadata v31

### ISSUE THREAD

**Issue by commonuserlol** [SamboyCoding/AudicaShredder#297]
Hi, sorry for the wrong place for the issues. I am using your PR for Il2CppInspector for metadata v29. Unfortunately most games use the newer version. So fields placed in wrong order and processing fails. Is there any chance that you will look into?

**Comment by SamboyCoding** [comment]
There is no metadata v31. 

Edit for posterity: yes there is, unity added it in a minor version for some reason.

**Comment by commonuserlol** [comment]
https://github.com/Perfare/Il2CppDumper/issues/797, tho Il2CppDumper kinda "died"

**Comment by SamboyCoding** [comment]
Custom engine or something. There is not - as of unity 6 - a metadata v31. 

Edit: As above, yes there is, in a minor version of 2022.3.

**Comment by commonuserlol** [comment]
So metadata is obfuscated? I had that with some games, they all using unity 2022+ with error:
```
Il2CppInspector Command-Line Edition
Version 2021.1+a165b63b5aecb76c50b7ddb435b9d35bf7a44fe7
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Using plugin: IL2CPP API Discovery
Using plugin: Binary metadata field order deobfuscator
Using plugin: Metadata strings XOR decryptor
Using plugin: Binary file XOR decryptor
Extracting metadata from (archive)/assets/bin/Data/Managed/Metadata/global-metadata.dat
Detected metadata version 29
Extracting binary from lib/arm64-v8a/libil2cpp.so
Processed XXXXXX relocations
Plugin Binary file XOR decryptor: Detecting encryption
Container format: ELF64
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Symbol table(s) found with XXX entries
No matches in symbol table
No matches via code heuristics
Required structures acquired from data heuristics
CodeRegistration struct found at 0x000000000XXXXXXX (file offset 0x0XXXXXXX)
MetadataRegistration struct found at 0x000000000XXXXXXX (file offset 0x0XXXXXXX)
The detected Il2CppCodeRegistration / Il2CppMetadataRegistration structs do not pass validation. This may mean that their fields have been re-ordered as a form of obfuscation and Il2CppInspector has not been able to restore the original order automatically. Consider re-ordering the fields in Il2CppBinaryClasses.cs and try again.
Analyze IL2CPP data: 100.20 sec
```

**Comment by commonuserlol** [comment]
Just tried Cpp2IL, works unlike Il2CppInspector

**Comment by SamboyCoding** [comment]
> Detected metadata version 29

from your il2cppinspector log

no idea what dumper is doing or where it's getting 31 from but this is just v29

**Comment by commonuserlol** [comment]
What about minor versions of v29? Can we get exact version (29.1, 29.2, ...) without unity version like inspector does?

**Comment by SamboyCoding** [comment]
`--verbose` will log minor version.

**Comment by commonuserlol** [comment]
I'm talking about il2cppinspector, else can/will Cpp2IL generate stuff for disassembler like Ghidra or IDA?

**Comment by YogeLike** [comment]
> Custom engine or something. There is not - as of unity 6 - a metadata v31.

I test unity6 and unity 22.3.35f1, it is confused that unity 6 are metadata v29 and unity22.3.35f1 are metadata v31

**Comment by commonuserlol** [comment]
Cpp2IL now have v31 support
