### ISSUE TITLE
The latest version of the artifact does not provide RVA, Offset and VA addresses

### ISSUE THREAD

**Issue by MikaCybertron** [SamboyCoding/AudicaShredder#302]
Hi sir, i tried the latest artifacts, but seems it does not provide RVA, Offset and VA addresses when dump the il2cpp + metadata 
https://github.com/SamboyCoding/Cpp2IL/actions/runs/9648488965

![image](https://github.com/SamboyCoding/Cpp2IL/assets/45533977/905857cf-82e3-4044-9102-2b6647f98bfe)

normally it should be like this
![image](https://github.com/SamboyCoding/Cpp2IL/assets/45533977/23310ee7-efdb-4744-a8f9-00a5624742aa)

but i wish you could generate the dump.cs too since the released version does not provide it after dump

**Comment by SamboyCoding** [comment]
`--use-processor attributeinjector`.
