### ISSUE TITLE
more metadata

### ISSUE THREAD

**Issue by ArjixWasTaken** [SamboyCoding/AudicaShredder#308]
I understand that it is difficult to convert ISIL into CIL, and that it is [not a priority](https://github.com/SamboyCoding/Cpp2IL/issues/223).
So the next best thing would be to include in comments the raw assembly (or ISIL?) of each method's body.

e.g.

```c#
public class Example {
    public void doSomething() {
        /*
            Memory address: 0xffffff;
            Assembly flavour: arm64;

            Code:
                - mov  x0, #1
                - ldr     x1, =msg
                - ldr     x2, =len
                - mov  w8, #64
                - svc    #0
        */
        throw null;
    }
}
```

I think this would save huge amounts of time and would make manual recovery much more manageable and tidier.

**Comment by ArjixWasTaken** [comment]
this would only apply to the `diffable-cs` output format

**Comment by SamboyCoding** [comment]
There is `--output-as isil` to just dump isil for each method
