### ISSUE TITLE
Invalid interface method implementations

### ISSUE THREAD

**Issue by thegu5** [SamboyCoding/AudicaShredder#310]
This was already mentioned in #cpp2il-support, I'm making this issue for organization.

example:
![image](https://github.com/SamboyCoding/Cpp2IL/assets/58223632/96a8a7ec-8814-4ab2-a0cd-4d27559894b2)
![image](https://github.com/SamboyCoding/Cpp2IL/assets/58223632/3ea3ad9f-671b-4993-bb69-0bba40e280da)
The method in the interface is public, but the method in the implementing class is private, causing the type to be invalid
> Method 'OnBeforeSerialize' in type 'UnityEngine.Events.UnityEvent`1' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

(this specific example's error is because UnityEvent`1 extends UnityEventBase which implements ISerializationCallbackReceiver, and it doesn't see the method impl in UnityEventBase)

https://github.com/Unity-Technologies/UnityCsReference/blob/c4a2a4d90d91496bf3d4602778223a0e660c2a56/Runtime/Export/UnityEvent/UnityEvent.cs#L743

**Comment by ds5678** [comment]
From my perspective, everything is fine, except for your decompiler. That's an explicit interface implementation, so it's supposed to be private. It's just not supposed to show an access modifier in the source code.

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation

**Comment by SamboyCoding** [comment]
I'm guessing one possibility is that the explicit implementation info is not being set (it's a separate field to specify it should inherit from the interface) and so ILSpy is decompiling it wrong. That or one of the combinations of flags (`private final hidebysig specialname newslot virtual`) is missing.

**Comment by thegu5** [comment]
> explicit implementation info is not being set

Looked at it again, this seems to be the case (?)

Correct example ([sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAobAOwxigDMBDMGAAgEF2BvK9ge0Ip2AWRgYAFhAAmACgCUAbioBfKiXYAhdiC69+g4VwB04qbMW91lVUA=)):
```
    .method private final hidebysig newslot virtual 
        instance void A.Method () cil managed 
    {
        .override method instance void A::Method()
        .maxstack 8

        IL_0000: ret
    }
```
Cpp2IL output, missing `.override`:
```
	.method private final hidebysig newslot virtual 
		instance void UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize () cil managed 
	{
		.maxstack 8

		IL_0000: ldnull
		IL_0001: throw
	}
```

**Comment by SamboyCoding** [comment]
Yup ok, this is an old issue that's resurfaced then.
