### ISSUE TITLE
Failed to export game content: The given key 'T' was not present in the dictionary.

### ISSUE THREAD

**Issue by cyberangel67** [SamboyCoding/AudicaShredder#33]
Are there logs to this?

If not all I can tell you is that is what I got for one game, I can view all the assets, just that is the error when I try to export.

**Comment by SamboyCoding** [comment]
Is this part of AssetRipper? Cpp2IL doesn't have any "export" function.

**Comment by cyberangel67** [comment]
Oh was wondering what happend, sorry I entered this in the wrong place.
