### ISSUE TITLE
Any way to run this on x86 apks?

### ISSUE THREAD

**Issue by RealIndica** [SamboyCoding/AudicaShredder#36]
Trying to restore some IL on an old APK I have that uses x86 ELF.

Any way I can do this?

**Comment by SamboyCoding** [comment]
Woah, I wasn't aware there *were* any x86 APKs. It should be doable... Can you send me the apk (or at least the name and version) so I can test it and add support myself?

**Comment by RealIndica** [comment]
Of course :)

https://drive.google.com/file/d/1uke5b0EfF9b7mGAWPSwtMD-Y4H6--Uiw/view?usp=sharing

**Comment by SamboyCoding** [comment]
Sorry, I meant to comment this at the time but it slipped my mind - the link was dead mere minutes after you sent it due to a violation of google's TOS.

**Comment by rananaveed123** [comment]
Download All Apk mods for free from our site and enjoy games and streaming apps.
<a href="https://apkzoon.com/">https://apkzoon.com/</a>
