### ISSUE TITLE
BoxValueAction does not allow Enums as a destination type

### ISSUE THREAD

**Issue by gompoc** [SamboyCoding/AudicaShredder#37]
Appeared in the Melonloader discord server, decided to check it out against the latest build on github
Game: Dynast.io
Log: [out.log](https://github.com/SamboyCoding/Cpp2IL/files/7253625/out.log)

**Comment by SamboyCoding** [comment]
Okay this is a two parter, so I'll fix the underlying issue eventually but not now, but I'm noting here that the parent issue is that the BoxValueAction for x86 does not seem to allow boxing to an enum type - the type which is failing is PuppetteerSharp.DOMWorldType, which you can see [here](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/DOMWorldType.cs#L7) has the enum value of `Other` as the second argument (it's actually params, but hey) to the constructor of JsonConverterAttribute, but that's not being picked up by the analysis engine, so it's been put in as a null value, which can't be used (in the way it's being generated) in a custom attribute.

Solution for now is just to fail the custom attribute generation, which will cause a fallback attribute to be generated, bypassing the null ref exception.

**Comment by SamboyCoding** [comment]
Workaround implemented in https://github.com/SamboyCoding/Cpp2IL/commit/1b834bef6f8cc0310a87f7d8e15f9e5f7a735e3d, which also addresses all the other exceptions in that log.

**Comment by SamboyCoding** [comment]
Closing as this will hopefully be addressed by the rewrite
