### ISSUE TITLE
Compiler generated methods without a body can cause issues with certain decompilers 

### ISSUE THREAD

**Issue by gompoc** [SamboyCoding/AudicaShredder#46]
Older decompilers such as dnSpy will throw an exception when decompiling methods that make use of compiler generated methods without method bodies. In the case that cpp2il succeeds in analyzing the compiler generated method it'll decompile fine. A solution to this could possibly be to emit method bodies that are similar to the bodies that are emitted for dummy dlls with analysis turned off and then adding a "FailedToAnalyse" attribute or something onto the method.

**Comment by SamboyCoding** [comment]
This is done now in https://github.com/SamboyCoding/Cpp2IL/commit/87d8b12e333b07901daa99fee998f48441692c79 - the body now throws an exception.
