### ISSUE TITLE
Creates empty functions

### ISSUE THREAD

**Issue by trsh** [SamboyCoding/AudicaShredder#71]
I was decompiling some game. It dumped the dlls. When viewing with sply or dnSpy it shows all function but their bodies are empty.

**Comment by SamboyCoding** [comment]
Read the README, you're not passing in the correct command line options.

**Comment by trsh** [comment]
@SamboyCoding I did read it. I use only 

--game-path
--exe-name

can you point me to what I am missing? It's not clear from the Readme.

**Comment by SamboyCoding** [comment]
I promise you the readme is clear. I refer people to it because it comes with some disclaimers and further information, but as a starting point, you want `--experimental-enable-il-to-assembly-please`.

**Comment by MatthewOGuerra** [comment]
happen to me 2

**Comment by Rabadash8820** [comment]
@SamboyCoding FWIW, I am also getting empty methods when I decompile an APK generated by Unity 2021.3.16f1 with Cpp2IL 2022.0.7. I've tried the `--experimental-enable-il-to-assembly-please` and `--just-give-me-dlls-asap-dammit` options (great names btw 😆), but both are generating methods without bodies when I open the generated DLLs in ILSpy or dnSpy. I'm wondering if the issue has to do with Cpp2IL not using the ideal architecture (x86, ARMv8, etc.), as I see no options to specify which architecture is decompiled, but your README indicates that some architectures (at least x86_64) are not supported.

If nothing else, it would be really helpful if your README explained (or perhaps had links to _other_ sources that explain) why the decompiled methods might be empty.

**Comment by SamboyCoding** [comment]
If the APK is Armv7 there is no output right now as armv7 isn't supported. If the dll you're looking at isn't assembly-csharp you need to use `--run-analysis-for-assembly` as detailed in the readme. Those are the only two cases you should have empty methods, assuming you've got the options you mentioned enabled.

**Comment by Rabadash8820** [comment]
@SamboyCoding Thanks for the quick reply! It was not clear to me that the `--run-analysis-for-assembly` flag was required (kinda makes me wonder what the point of `--skip-analysis` is then?), but adding it did indeed add some method bodies! Unfortunately, now i looks like every method in my decompiled type has the following body:

```cs
//Discarded unreachable code: IL_0022
//IL_000b: Expected O, but got F4
//IL_0016: Expected I, but got F4
//IL_0021: Expected I, but got F4
_rectTransform = (RectTransform?)0f;
((UnityEngine.Object)this).m_CachedPtr = (IntPtr)0f;
((UnityEngine.Object)this).m_CachedPtr = (IntPtr)0f;
```

I tried adding `--analysis-level 0` to save "everything", but that doesn't change the body. Do you have any insight on what those comments mean? Also, regarding architecture, my APK contains all 4 architectures under `lib/` (arm64-v8a, armeabi-v7a, x86, and x86_64), so which would it be decompiling in that case? Thanks again for your help!

**Comment by SamboyCoding** [comment]
`--run-analysis-for-assembly` specifies which assembly to run for, other than the default of Assembly-CSharp. By contrast, `--skip-analysis` disables analysis entirely. The `--analysis-level` flag is only for the generated method dump files, not for the code saved to the DLL. And finally, the APK searching prioritises the best-implemented instruction set, so in this case that would be x86_64.

**Comment by Rabadash8820** [comment]
Interesting, thanks for clarifying. I'm trying to decompile a DLL from `libil2cpp.so` called UnityUtil. So, based on the above comments in the decompiled DLL, is the issue that I need to run analysis on all of the assemblies that UnityUtil _references_ also? Otherwise, how do I know to which "unreachable code" it's referring, or what "Expected X, but got F4" means?

**Comment by SamboyCoding** [comment]
No, the issue in that case is just that my decompilation is imperfect. Those messages indicate incorrect code generation. I suggest looking into the aforementioned method dump text files - they often have more detail in the pseudocode.
