### ISSUE TITLE
Unsupported metadata version

### ISSUE THREAD

**Issue by iViscosity** [SamboyCoding/AudicaShredder#72]
I think this is more of an issue with the game itself and not the program, but I'm getting the following error:

```
[Info] [Program] Running on Win32NT
[Warn] [Program] Fail once: Unity version of provided executable is [0, 0, 0]. This is probably not the correct version. Retrying with alternative method...
[Info] [Program] Determined game's unity version to be 2019.4.17
[Info] [Library] Initializing Metadata...
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.FormatException: Unsupported metadata version found! We support 24-29, got 6042200
   at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[] bytes, Int32[] unityVer)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

Not sure why the version number is that... but HxD shows the same result:

![image](https://user-images.githubusercontent.com/20390370/157329620-5c4a7bbe-d30f-4969-bdfd-87a5ca605bd7.png)

I'm not very familiar with decompiling games in the first place so I don't really know where to go from here. From the research I've been able to do, it may be that the metadata is obfuscated in some way, but it has the `AF 1B B1 FA` header, which _indicates_ an unobfuscated metadata file, but not necessarily guarantees. Any thoughts/suggestions?

For reference, the game is `Rise of Kingdoms` (originally a mobile game, ported to PC a few months ago).

**Comment by SamboyCoding** [comment]
Yes sounds like a custom metadata file.

**Comment by SamboyCoding** [comment]
You'd be best reading djkaty's blog posts on some approaches you can try from here to get this to load if you want to put the effort in

**Comment by iViscosity** [comment]
Hi, sorry to comment on this again so late. I am just still interested in figuring this out. I've read through some of those blogs (thanks for the info!) but to no avail. I thought I'd post the metadata file here in case anyone else would like to take a look. 

I can't upload .dat files to GitHub, so I put it in Drive: https://drive.google.com/file/d/1fVl_duOp2uUF05Vo9QTXcMBTPqJjZ-p9/view?usp=sharing

I hope it's okay that I share that here. Otherwise I can share it elsewhere.

Edit: The version number has increased from some updates. Not sure if that gives any clue to how it is customized or not.
