### ISSUE TITLE
Failed to find exe file.

### ISSUE THREAD

**Issue by WuFan** [SamboyCoding/AudicaShredder#74]
[Fail] [Program] Execution Failed:Invalid game-path or exe-name specified.

System: Win 10 x64
Build :Unity 2017.2.1 f1  Standalone

**Comment by SamboyCoding** [comment]
Going to need more information than that. Please provide full output as well as a screenshot of the folder you're providing

**Comment by WuFan** [comment]
Ok.

![img1](https://user-images.githubusercontent.com/2026798/159158135-80e9e11e-6e9b-46db-835e-7c224352a1b8.png)

![img2](https://user-images.githubusercontent.com/2026798/159158198-a42ea3a1-ec76-406f-9a51-a4cdcc2feebe.png)

Thanks.

**Comment by SamboyCoding** [comment]
Move cpp2il out of the game folder

**Comment by WuFan** [comment]
same error.

Path
--Cpp2IL-Win.exe
--Game
----UEGame.exe
----UEGame_Data
----UnityPlayer.dll

**Comment by SamboyCoding** [comment]
Wait, that game isn't il2cpp. It would have a GameAssembly.dll file if it was.

**Comment by daviddprtma** [comment]
> Wait, that game isn't il2cpp. It would have a GameAssembly.dll file if it was.

hello. the game that I want to inject using cpp2il  have gameaasembly.dll . so how I can inject it through cpp2il? I need your assistance. Thanks.
