### ISSUE TITLE
Dummy DLL's function generic parameter is incorrect

### ISSUE THREAD

**Issue by YinTianer** [SamboyCoding/AudicaShredder#96]
Cpp2IL:
![屏幕截图 2022-04-07 062153](https://user-images.githubusercontent.com/103054683/162082166-32f3002f-941d-460d-89d4-3338438dbc7c.png)
Il2CppDumper:
![屏幕截图 2022-04-07 062221](https://user-images.githubusercontent.com/103054683/162082140-8dd9bb43-9bc9-4b18-b894-8d33b4fc9ed5.png)
public void RegisterHandler<T>(Action<T> handler)
It's Milestone 2022.0.2

**Comment by SamboyCoding** [comment]
Your issue seems to have lost some of the detail, perhaps due to markdown. It might be best if you upload a screenshot. Also, I assume you mean the rewrite (2022.1 pre-release) builds of cpp2il?

**Comment by SamboyCoding** [comment]
Your issue seems to have lost some of the detail, perhaps due to markdown. It might be best if you upload a screenshot. Also, I assume you mean the rewrite (2022.1 pre-release) builds of cpp2il?

**Comment by SamboyCoding** [comment]
Hold on, if this is a pre-release build, how does the method have a body? The pre-release builds do not have any functionality to create method bodies.

**Comment by YinTianer** [comment]
I'm wrong. It's the latest releases version and I used the "--experimental-enable-il-to-assembly-please"  Option

**Comment by SamboyCoding** [comment]
Is the parameter correct if you choose not to output IL? Also, is the parameter correct on the latest pre-release build?

**Comment by YinTianer** [comment]
I compiled the pre-release build version myself, and it seems to have no problem
